version: "3.8"

services:
  app:
    container_name: docker-react
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    ports:
      - 8080:8080
