version: "3.8"

services:
  app:
    image: front-ui
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/client"
      - "./client/node_modules"
    ports:
      - 3000:3000
    stdin_open: true
