version: "3.8"

services:
  app:
    image: front-ui
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    ports:
      - 3000:3000
